[project]
name = "kata-olivanders"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "coverage>=7.13.4",
    "pytest>=9.0.2",]